// id, url and description are simple and automaticaly generated by GraphQL
// We need to explicitly implement 'postedBy'
function postedBy(parent, args, context, info) {
  // fetch the link and invoke postedBy()
  return context.prisma.link({ id: parent.id }).postedBy()
}

function votes(parent, args, context, info) {
  return context.prisma.link({ id: parent.id }).votes()
}

module.exports = {
  postedBy,
  votes
}